export const data = [
    {
        id: 1,
        firstname: 'Javlon',
        lastname: 'Mansurov',
        username: 'Javlon_Mansurov',
        email: 'javlon32@gmail.com',
        tel: '+99 899 329 21 93',
        country: 'Uzbekistan',
        province: 'Toshkent',
        district: 'Yunusobod',
    },
    {
        id: 2,
        firstname: 'Javlon',
        lastname: 'Nurmatov',
        username: 'Mansur_Nurmatov',
        email: 'Nurmat@gmail.com',
        tel: '+99 899 423 24 23',
        country: 'Uzbekistan',
        province: 'Toshkent',
        district: 'Yunusobod',
    },
    {
        id: 3,
        firstname: 'Sherali',
        lastname: 'Bolqiboyer',
        username: 'Sherali_Bolqiboyer',
        email: 'sherali43@gmail.com',
        tel: '+99 899 329 21 93',
        country: 'Uzbekistan',
        province: 'Toshkent',
        district: 'Qoyliq',
    },
    {
        id: 4,
        firstname: 'Ravshan',
        lastname: 'Qayumov',
        username: 'Ravshan_Qayumov',
        email: 'javlon32@gmail.com',
        tel: '+99 899 329 21 93',
        country: 'Uzbekistan',
        province: 'Toshkent',
        district: 'Mirobod',
    },
    {
        id: 5,
        firstname: 'Olimjon',
        lastname: 'Hikmatov',
        username: 'Olimjon_Hikmatov',
        email: 'olimjon@gmail.com',
        tel: '+99 899 429 21 92',
        country: 'Uzbekistan',
        province: 'Toshkent',
        district: 'Chilonzor',
    },
    {
        id: 6,
        firstname: 'Olimjon',
        lastname: 'Hikmatov',
        username: 'Olimjon_Hikmatov',
        email: 'olimjon@gmail.com',
        tel: '+99 899 429 21 92',
        country: 'Uzbekistan',
        province: 'Toshkent',
        district: 'Chilonzor',
    },
]